### ISSUE TITLE
Can this be used in Django 5?

### ISSUE THREAD

**Issue by tehfink** [team23/async-signals#22]
Sorry for the stupid question

**Comment by ddanier** [comment]
Is is a Python package, so it can be used with Django. You could even define similar signals to what Django has. You could even send those signal in for example `asave()` if you want.

My Question would be: Why would you want to do that? As of Django 5.0 signals and their receivers can already be async? You don't need an external library for this in Django... It makes way more sense to use what Django already provides.

See https://docs.djangoproject.com/en/5.0/topics/signals/
